# Generated by Django 5.2.7 on 2025-10-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', '')], default='LIGHT', max_length=20)),
                ('account_type', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'PRO'), ('MAX', 'MAX')], default='FREE', max_length=20)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
