# Generated by Django 5.2.7 on 2025-10-23 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("DARK", "Dark"), ("LIGHT", "Light")],
                        default="LIGHT",
                        max_length=20,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("FREE", "Free"), ("PRO", "PRO"), ("MAX", "MAX")],
                        default="FREE",
                        max_length=20,
                    ),
                ),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "settings",
            },
        ),
    ]
