# Generated by Django 5.2.7 on 2025-10-22 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0002_setting_user"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="theme",
            field=models.CharField(
                choices=[("DARK", "Dark"), ("LIGHT", "Light")],
                default="LIGHT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
    ]
